===========<class 'dynamic_network_architectures.architectures.unet.ResidualEncoderUNet'>===========
ds wegihts: [0.53333333 0.26666667 0.13333333 0.06666667]
This is the configuration used by this training:
Configuration name: 2d
 {'data_identifier': 'nnUNetPlans_2d', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 49, 'patch_size': [256, 256], 'median_image_size_in_voxels': [256.0, 256.0], 'spacing': [1.0, 1.0], 'normalization_schemes': ['ZScoreNormalization', 'ZScoreNormalization', 'ZScoreNormalization'], 'use_mask_for_norm': [False, False, False], 'UNet_class_name': 'ResidualEncoderUNet', 'nnUNet_UNet': False, 'UNet_base_num_features': 32, 'my_net_class': 'unet_plus', 'n_conv_per_stage_encoder': [2, 2, 2, 2, 2, 2, 2], 'n_conv_per_stage_decoder': [2, 2, 2, 2, 2, 2], 'num_pool_per_axis': [6, 6], 'pool_op_kernel_sizes': [[1, 1], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2]], 'conv_kernel_sizes': [[3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3]], 'unet_max_num_features': 512, 'resampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_data_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'batch_dice': True}
These are the global plan.json settings:
 {'dataset_name': 'Dataset122_ISIC2017', 'plans_name': 'nnUNetPlans', 'original_median_spacing_after_transp': [999.0, 1.0, 1.0], 'original_median_shape_after_transp': [1, 256, 256], 'image_reader_writer': 'NaturalImage2DIO', 'transpose_forward': [0, 1, 2], 'transpose_backward': [0, 1, 2], 'experiment_planner_used': 'ExperimentPlanner', 'label_manager': 'LabelManager', 'foreground_intensity_properties_per_channel': {'0': {'max': 255.0, 'mean': 160.1475372314453, 'median': 164.0, 'min': 0.0, 'percentile_00_5': 34.0, 'percentile_99_5': 252.0, 'std': 41.12111282348633}, '1': {'max': 255.0, 'mean': 111.18875122070312, 'median': 113.0, 'min': 0.0, 'percentile_00_5': 10.0, 'percentile_99_5': 222.0, 'std': 42.475669860839844}, '2': {'max': 255.0, 'mean': 91.16386413574219, 'median': 90.0, 'min': 0.0, 'percentile_00_5': 5.0, 'percentile_99_5': 207.0, 'std': 42.03706359863281}}}
2024-02-26 13:45:13.494425: unpacking dataset...
2024-02-26 13:45:19.433992: unpacking done...
2024-02-26 13:45:19.436341: do_dummy_2d_data_aug: False
2024-02-26 13:45:19.455181: Using splits from existing split file: /afs/crc.nd.edu/user/y/ypeng4/data/preprocessed_data/Dataset122_ISIC2017/splits_final.json
2024-02-26 13:45:19.456968: The split file contains 1 splits.
2024-02-26 13:45:19.457846: Desired fold for training: 3
2024-02-26 13:45:19.458629: INFO: You requested fold 3 for training but splits contain only 1 folds. I am now creating a random (but seeded) 80:20 split!
2024-02-26 13:45:19.471281: This random 80:20 split has 1720 training and 430 validation cases.
==================batch size: 2===================
2024-02-26 13:45:19.562047: Unable to plot network architecture:
2024-02-26 13:45:19.563174: No module named 'hiddenlayer'
2024-02-26 13:45:19.619799:
2024-02-26 13:45:19.620893: Epoch 0
2024-02-26 13:45:19.621713: start training, 250
using pin_memory on device 0
2024-02-26 13:45:26.370149: finished training
2024-02-26 13:45:26.726199: Using splits from existing split file: /afs/crc.nd.edu/user/y/ypeng4/data/preprocessed_data/Dataset122_ISIC2017/splits_final.json
2024-02-26 13:45:26.728499: The split file contains 1 splits.
2024-02-26 13:45:26.729469: Desired fold for training: 3
2024-02-26 13:45:26.730333: INFO: You requested fold 3 for training but splits contain only 1 folds. I am now creating a random (but seeded) 80:20 split!
2024-02-26 13:45:26.744399: This random 80:20 split has 1720 training and 430 validation cases.
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/y/ypeng4/nnUNet/nnunetv2/run/run_training.py", line 306, in <module>
    run_training_entry()
  File "/afs/crc.nd.edu/user/y/ypeng4/nnUNet/nnunetv2/run/run_training.py", line 300, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/afs/crc.nd.edu/user/y/ypeng4/nnUNet/nnunetv2/run/run_training.py", line 231, in run_training
    nnunet_trainer.run_training(dataset_id=dataset_id)
  File "/afs/crc.nd.edu/user/y/ypeng4/nnUNet/nnunetv2/training/nnUNetTrainer/retinaTrainer.py", line 150, in run_training
    self.real_validation_retina()
  File "/afs/crc.nd.edu/user/y/ypeng4/nnUNet/nnunetv2/training/nnUNetTrainer/retinaTrainer.py", line 281, in real_validation_retina
    ref_arr = sitk.GetArrayFromImage(sitk.ReadImage(ref_file))
  File "/afs/crc.nd.edu/user/y/ypeng4/.conda/envs/python38/lib/python3.8/site-packages/SimpleITK/extra.py", line 375, in ReadImage
    return reader.Execute()
  File "/afs/crc.nd.edu/user/y/ypeng4/.conda/envs/python38/lib/python3.8/site-packages/SimpleITK/SimpleITK.py", line 8430, in Execute
    return _SimpleITK.ImageFileReader_Execute(self)
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:97:
sitk::ERROR: The file "/afs/crc.nd.edu/user/y/ypeng4/data/preprocessed_data/Dataset122_ISIC2017/gt_segmentations/ISIC_0000001.nii.gz" does not exist.
2024-02-26 13:45:28.342687: predicting ISIC_0000001 took 1.57 s